# This gist contains the config for rubocop-performance >1.11 / rubocop >1.22, for ruby 3.0: https://gist.github.com/apptweak-ci/2aca83afffbcbe0c0bca2beaab1500c0
inherit_from: https://gist.githubusercontent.com/apptweak-ci/2aca83afffbcbe0c0bca2beaab1500c0/raw/.rubocop.yml

require:
  - rubocop-rake
  - rubocop-yard

Gemspec/RequireMFA:
  Enabled: false
