# frozen_string_literal: true

module YARD
  module Handlers
    module C
      # Patch for YARD's C Base handler to correctly map C exception variables
      # to their corresponding Ruby class names.
      class Base < Handlers::Base
        # Temporary workaround until a proper fix can be applied to YARD master.
        alias namespace_for_variable_original namespace_for_variable

        # Overrides the original method to include custom mapping for C exception variables.
        # Falls back to the original implementation if no custom mapping is found.
        #
        # @param var [String] The C variable name.
        # @return [CodeObjects::NamespaceObject, nil] The corresponding namespace object or nil.
        def namespace_for_variable(var)
          patch_namespace_for_variable(var) ||
            namespace_for_variable_original(var)
        end

        private

          # Attempts to find a Ruby class name mapping for the given C variable.
          #
          # @param var [String] The C variable name.
          # @return [CodeObjects::Proxy, nil] A proxy object for the mapped class or nil.
          def patch_namespace_for_variable(var)
            name = PATCH_ERROR_NAME[var]
            # $stderr.puts "Mapped #{var} to #{name}" if name
            name.nil? ? nil : P(name)
          end

          # Generated by update_error_map.rb (Copy+past results)
          # Maps C exception variable names to their Ruby class names.
          PATCH_ERROR_NAME = {
            "rb_eException" => "Exception",
            "rb_eSystemExit" => "SystemExit",
            "rb_eFatal" => "fatal",
            "rb_eSignal" => "SignalException",
            "rb_eInterrupt" => "Interrupt",
            "rb_eStandardError" => "StandardError",
            "rb_eTypeError" => "TypeError",
            "rb_eArgError" => "ArgumentError",
            "rb_eIndexError" => "IndexError",
            "rb_eKeyError" => "KeyError",
            "rb_eRangeError" => "RangeError",
            "rb_eScriptError" => "ScriptError",
            "rb_eSyntaxError" => "SyntaxError",
            "rb_eLoadError" => "LoadError",
            "rb_eNotImpError" => "NotImplementedError",
            "rb_eNameError" => "NameError",
            "rb_eNoMethodError" => "NoMethodError",
            "rb_eRuntimeError" => "RuntimeError",
            "rb_eFrozenError" => "FrozenError",
            "rb_eSecurityError" => "SecurityError",
            "rb_eNoMemError" => "NoMemoryError",
            "rb_eEncodingError" => "EncodingError",
            "rb_eSystemCallError" => "SystemCallError"
          }.freeze
          private_constant :PATCH_ERROR_NAME
      end
    end
  end
end
